server:
  port: 8080
spring:
  application:
    name: student-document
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/healthmanager?&serverTimezone=GMT%2B8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  servlet:
    multipart:
      max-file-size: 5MB
  mvc:
    view:
      prefix: /pages/
      suffix: .html
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.jxau.studentdocument.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里配置
aliyun:
  oss: #存储
    endpoint: oss-cn-beijing.aliyuncs.com   # 域
    accessKeyId:    # 秘钥KeyId
    accessKeySecret:  # 秘钥KeySecret
    bucketName:   # 桶名
    url:   # 访问地址


